### ISSUE TITLE
Python version dependency is very limiting

### ISSUE THREAD

**Issue by busbaby** [voznik/streamlit-textcomplete#2]
I would love to use this component, but "streamlit-textcomplete==0.1.0 depends on Python>=3.11,<4.0".  My project is using 'Python 3.10.12'. I have not examined the code, but I find it hard to believe that 3.11 as a minimum is required.

**Comment by voznik** [comment]
this is probably fixable. I will try to include this change in next version

**Comment by voznik** [comment]
released new version, closing this issue

**Comment by busbaby** [comment]
Works great! Thank you

**Comment by busbaby** [comment]
> Works great! Thank you

Actually, it's not exactly. Installing streamlit-textcomplete added emoji==2.12.1 to my environment, which should not be necessary in order to use this component. Also, it upgraded my project's streamlit version from 1.34.0 to 1.36.0, which seems unnecessary as well.

**Comment by voznik** [comment]
I've updated the dependency configuration to ensure that the component works with Streamlit versions 1.34.0 and higher, without forcing an upgrade
