### ISSUE TITLE
Fuzzy Search Algorithm

### ISSUE THREAD

**Issue by MelihDarcanxyz** [voznik/streamlit-textcomplete#5]
Hi, firstly, thank you for this component.

The default search algorithm isn't working well for us. For example, we start the search with "prot...", it should return "protein". But it returns "something something protein something" to us. This probably stems from the fact that there are too many possible matches, and it returns the first few. Thus, we've turned to external algorithms. Right now, we're trying to use this component with a fuzzy search algorithm (https://github.com/krisk/fuse) as it is the most appropriate for our use case, but we couldn't make it work.

Do you have any ideas or suggestions on how to do that?

Thanks again for this component, it's really helpful. Have a nice day.

**Comment by voznik** [comment]
Hi @MelihDarcanxyz 
This component was developed with the purpose to be very simple yet very customizable per user needs, and thus it is completely up to you how to write search function which is passed then to front-end component
By saying "we couldn't make it work" - do you probably mean that  you were unable to use custom fuzzy search library as a dependency for you search function?

**Comment by MelihDarcanxyz** [comment]
Hi @voznik , thanks for update. Yes, that's what I meant. Despite even editing the source code, we had no luck using an external fuzzy search package. We probably couldn't figure it out.

First, we have to init the search algorithm:

```js
const fuse = new Fuse(suggestions, {
    includeScore: true,
    threshold: 0.3,
    shouldSort: true,
    distance: 100,
});
```

Then, we need to call the search function whenever the textcomplete triggers a search function.

```js
function autocomplete(val) {
    // 0, 20 is arbitrarily choosen numbers. They are configured with textcomplete too.
    const results = fuse.search(val).slice(0, 20)
    return results
}
```

I typed this on the fly, so there may be syntax errors. But the logic is the same.

Thanks in advance, and thanks again for this component.

**Comment by voznik** [comment]
hey @MelihDarcanxyz congrats, I decided not to argue about anything and implemented default search using Fuse.js
see example.py with default emoji strategy and new company_name strategy

version 0.2.0 is available on pypi

hope this will help

**Comment by MelihDarcanxyz** [comment]
Wow, didn't expect that. Will definitely be of help, have a nice day!

**Comment by voznik** [comment]
@MelihDarcanxyz if you have time - would you be open to contribute to this repo and create functionality to generate/update CHANGELOG, and update actions workflow to also create github release during release ?

**Comment by MelihDarcanxyz** [comment]
@voznik Sure, but I'll need to understand what to do or how to do properly beforehand. How can we communicate?

Edit: I think I know how to properly handle the stuff you mentioned. Will send a PR when I have time.
